base_url = "https://sitc.community"
compile_sass = true
highlight_code = true
build_search_index = true
theme = "hyde"
title = "SITC"
description = "Сайт сообщества работников сферы ИТ Самары и области - Samara IT Community"
generate_rss = true

[extra]
# Put all your custom variables here
hyde_menu_links = [
    {url = "/people", name = "Люди"},
    {url = "/events", name = "Мероприятия"},
    {url = "/communities", name = "Сообщества"},
    {url = "/resources", name = "Ресурсы"},
    {url = "/study", name = "Обучение"},
]
hyde_social_links = [
    {url = "https://vk.com/samara_it_community", name = "Группа Вконтакте", logo = "/social/vk_bw_logo.png"},
    {url = "https://twitter.com/TcommunityI", name = "Twitter", logo = "/social/Twitter_Logo_Blue.png"},
    {url = "https://www.instagram.com/itc_samara/", name = "Instagram", logo = "/social/instagram_black.png"},
    {url = "https://t.me/Samara_IT_Community", name = "Telegram Канал", logo = "/social/telegram.png"},
    {url = "https://www.youtube.com/channel/UCWwGzRCrnCWRVQ_UlpwZQMA", name = "Youtube Канал", logo = "/social/youtube.png"},
    {url = "https://www.patreon.com/samara_it_community", name = "Patreon", logo = "/social/patreon.png"},
]
